# this can be any name
name: BlogAPI test

# specify the on which action this action should work on
on:
  # specify the branches this action works on
  push:
    # this is also a valid syntax
    # branches: ["master", "main"]
    branches:
      - "main"
      - "master"

jobs:
  # job name can be anything
  job1:
    # specify the OS to run on.
    runs-on: ubuntu-latest
    # steps, things done. Each step has a name that is used to identify the step
    steps:
      - name: Pull repo
        # https://github.com/orgs/actions/repositories?type=all
        uses: actions/checkout@v3
      # - name: say hello
      #   run: echo "hello world"

      # install python3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt

  job2:
    runs-on: ubuntu-latest
    needs: [job1]

    steps:
      - name: Deploy application
        run: echo "deploying application"
        
          